#include "nvim.h"
int luaopen_catppuccin_compiled_frappe(lua_State *lstate) {
	o("termguicolors", True);
	g("colors_name", s("catpussy"));
	Error err = ERROR_INIT;
	KeyDict_highlight o;

o("background", s("dark"));
g("terminal_color_2", s("#A6D189"));
g("terminal_color_10", s("#A6D189"));
g("terminal_color_3", s("#E5C890"));
g("terminal_color_11", s("#E5C890"));
g("terminal_color_4", s("#8CAAEE"));
g("terminal_color_12", s("#8CAAEE"));
g("terminal_color_5", s("#F4B8E4"));
g("terminal_color_13", s("#F4B8E4"));
g("terminal_color_6", s("#99D1DB"));
g("terminal_color_14", s("#99D1DB"));
g("terminal_color_7", s("#c6d0f5"));
g("terminal_color_15", s("#c6d0f5"));
g("terminal_color_0", s("#737994"));
g("terminal_color_8", s("#838ba7"));
g("terminal_color_1", s("#E78284"));
g("terminal_color_9", s("#E78284"));
o = (KeyDict_highlight){ .sp = s("#99D1DB"), .underline = True };
c("DiagnosticUnderlineInfo");
c("LspDiagnosticsUnderlineInformation");
api_free_keydict_highlight(&o);
h("CmpItemAbbrDeprecated", .fg = s("#737994"), .strikethrough = True);
h("LspDiagnosticsVirtualTextError", .fg = s("#E78284"), .italic = True);
h("LspDiagnosticsVirtualTextInformation", .fg = s("#99D1DB"), .italic = True);
o = (KeyDict_highlight){ .sp = s("#E5C890"), .underline = True };
c("DiagnosticUnderlineWarn");
c("LspDiagnosticsUnderlineWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .sp = s("#81C8BE"), .underline = True };
c("DiagnosticUnderlineHint");
c("LspDiagnosticsUnderlineHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#292C3C"), .fg = s("#51576d") };
c("TabLine");
c("StatusLineNC");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#303446"), .fg = s("#c6d0f5") };
c("Normal");
c("NormalNC");
c("mkdCodeDelimiter");
api_free_keydict_highlight(&o);
h("ErrorMsg", .bold = True, .fg = s("#E78284"), .italic = True);
h("Folded", .bg = s("#51576d"), .fg = s("#8CAAEE"));
h("SignColumnSB", .bg = s("#232634"), .fg = s("#51576d"));
h("Substitute", .bg = s("#51576d"), .fg = s("#F4B8E4"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#EF9F76") };
c("MatchParen");
c("markdownHeadingDelimiter");
api_free_keydict_highlight(&o);
h("NormalSB", .bg = s("#232634"), .fg = s("#c6d0f5"));
h("Pmenu", .bg = s("#3B3F52"), .fg = s("#949cbb"));
h("Search", .bg = s("#506373"), .fg = s("#c6d0f5"));
h("EndOfBuffer", .fg = s("#303446"));
h("IncSearch", .bg = s("#8FC1CC"), .fg = s("#292C3C"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#c6d0f5") };
c("ModeMsg");
c("CmpItemAbbrMatch");
c("CmpItemAbbrMatchFuzzy");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F2D5CF") };
c("WinBar");
c("@property.cpp");
api_free_keydict_highlight(&o);
h("SpellBad", .sp = s("#E78284"), .undercurl = True);
h("SpellCap", .sp = s("#E5C890"), .undercurl = True);
h("htmlH1", .bold = True, .fg = s("#F4B8E4"));
h("SpellRare", .sp = s("#A6D189"), .undercurl = True);
h("DiffAdd", .bg = s("#455052"));
h("DiffDelete", .bg = s("#514251"));
h("debugBreakpoint", .bg = s("#303446"), .fg = s("#737994"));
h("Todo", .bg = s("#E5C890"), .bold = True, .fg = s("#303446"));
o = (KeyDict_highlight){ .sp = s("#E78284"), .underline = True };
c("DiagnosticUnderlineError");
c("LspDiagnosticsUnderlineError");
api_free_keydict_highlight(&o);
h("DiffText", .bg = s("#414964"));
o = (KeyDict_highlight){ .link = s("Type") };
c("@type");
c("Typedef");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#BABBF1") };
c("@text.reference");
c("NvimTreeRootFolder");
api_free_keydict_highlight(&o);
h("Bold", .bold = True);
h("@namespace", .fg = s("#BABBF1"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#EA999C"), .italic = True };
c("@parameter");
c("@text.emphasis");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#c6d0f5"), .fg = s("#303446") };
c("Cursor");
c("lCursor");
c("CursorIM");
api_free_keydict_highlight(&o);
h("@comment", .link = s("Comment"));
o = (KeyDict_highlight){ .link = s("Special") };
c("Tag");
c("Debug");
c("Delimiter");
c("SpecialChar");
c("SpecialComment");
api_free_keydict_highlight(&o);
h("@character", .link = s("Character"));
h("@text.danger", .bg = s("#E78284"), .fg = s("#303446"));
h("@text.diff.add", .link = s("diffAdded"));
h("@text.diff.delete", .link = s("diffRemoved"));
h("Italic", .italic = True);
o = (KeyDict_highlight){ .fg = s("#81C8BE"), .italic = True };
c("@tag.attribute");
c("LspDiagnosticsVirtualTextHint");
api_free_keydict_highlight(&o);
h("GitSignsDeletePreview", .link = s("DiffDelete"));
o = (KeyDict_highlight){ .fg = s("#A6D189") };
c("String");
c("diffAdded");
c("markdownH3");
c("GitSignsAdd");
c("rainbowcol7");
c("TSRainbowGreen");
c("CmpItemKindUnit");
c("DashboardCenter");
c("CmpItemKindEnum");
c("CmpItemKindField");
c("@text.todo.checked");
c("CmpItemKindProperty");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#8CAAEE") };
c("@class");
c("MoreMsg");
c("@struct");
c("Question");
c("Function");
c("diffFile");
c("Directory");
c("@text.math");
c("qfFileName");
c("FloatBorder");
c("@label.json");
c("@field.yaml");
c("CmpItemKind");
c("rainbowcol4");
c("diffChanged");
c("TSRainbowBlue");
c("LspInfoBorder");
c("GlyphPalette4");
c("NvimTreeGitNew");
c("@property.toml");
c("CmpItemKindFile");
c("@string.special");
c("TelescopeBorder");
c("DashboardHeader");
c("CmpItemKindEvent");
c("@property.id.css");
c("CmpItemKindModule");
c("CmpItemKindFolder");
c("CmpItemKindMethod");
c("CmpItemKindStruct");
c("TelescopeMatching");
c("NvimTreeFolderName");
c("NvimTreeFolderIcon");
c("CmpItemKindOperator");
c("CmpItemKindFunction");
c("@text.environment.name");
c("CmpItemKindConstructor");
c("NvimTreeEmptyFolderName");
c("CmpItemKindTypeParameter");
c("NvimTreeOpenedFolderName");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#8CAAEE") };
c("Title");
c("htmlH2");
c("@text.title");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#EF9F76") };
c("Float");
c("Number");
c("Boolean");
c("@method");
c("Constant");
c("@constant");
c("diffNewFile");
c("@number.css");
c("@string.regex");
c("TSRainbowOrange");
c("CmpItemKindValue");
c("@constant.builtin");
c("@function.builtin");
c("@string.plain.css");
c("CmpItemKindConstant");
c("LspSignatureActiveParameter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#CA9EE6") };
c("@tag");
c("Macro");
c("Repeat");
c("Keyword");
c("Include");
c("Statement");
c("markdownH2");
c("@exception");
c("Conditional");
c("@type.tag.css");
c("@keyword.return");
c("TSRainbowViolet");
c("@keyword.function");
c("@keyword.operator");
c("CmpItemKindSnippet");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#81C8BE") };
c("@enum");
c("Character");
c("markdownH6");
c("rainbowcol2");
c("diffIndexLine");
c("healthSuccess");
c("TSRainbowCyan");
c("GlyphPalette6");
c("@text.literal");
c("GlyphPalette2");
c("CmpItemKindText");
c("@function.macro");
c("LspDiagnosticsHint");
c("DiagnosticSignHint");
c("CmpItemKindCopilot");
c("DiagnosticFloatingHint");
c("LspDiagnosticsDefaultHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#E78284") };
c("Error");
c("rainbowcol1");
c("diffRemoved");
c("healthError");
c("TSRainbowRed");
c("GlyphPalette9");
c("GlyphPalette1");
c("GitSignsDelete");
c("CmpItemKindColor");
c("@variable.builtin");
c("CmpItemKindKeyword");
c("NvimTreeGitDeleted");
c("LspDiagnosticsError");
c("DiagnosticSignError");
c("CmpItemKindReference");
c("CmpItemKindEnumMember");
c("DiagnosticFloatingError");
c("LspDiagnosticsDefaultError");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#E5C890") };
c("Type");
c("qfLineNr");
c("Structure");
c("WarningMsg");
c("markdownH4");
c("diffOldFile");
c("rainbowcol3");
c("StorageClass");
c("healthWarning");
c("GlyphPalette3");
c("@type.builtin");
c("GitSignsChange");
c("@typeParameter");
c("TSRainbowYellow");
c("CmpItemKindClass");
c("NvimTreeGitDirty");
c("DiagnosticSignWarn");
c("@property.class.css");
c("CmpItemKindInterface");
c("LspDiagnosticsWarning");
c("DiagnosticFloatingWarn");
c("LspDiagnosticsDefaultWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F4B8E4") };
c("Special");
c("PreProc");
c("@regexp");
c("markdownH5");
c("rainbowcol5");
c("@string.escape");
c("NvimTreeSymlink");
c("@text.environment");
c("DashboardShortCut");
c("NvimTreeOpenedFile");
api_free_keydict_highlight(&o);
h("DiagnosticWarn", .bg = s("NONE"), .fg = s("#E5C890"), .italic = True);
h("DiagnosticError", .bg = s("NONE"), .fg = s("#E78284"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#99D1DB") };
c("Operator");
c("@tag.delimiter");
c("DiagnosticSignInfo");
c("@punctuation.special");
c("DiagnosticFloatingInfo");
c("LspDiagnosticsInformation");
c("LspDiagnosticsDefaultInformation");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#474D61") };
c("IlluminatedWordText");
c("IlluminatedWordRead");
c("IlluminatedWordWrite");
api_free_keydict_highlight(&o);
h("CursorColumn", .bg = s("#292C3C"));
o = (KeyDict_highlight){ .fg = s("#c6d0f5") };
c("@text");
c("@variable");
c("SpecialKey");
c("CmpItemMenu");
c("GlyphPalette7");
c("NvimTreeImageFile");
c("IndentBlanklineContextChar");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#292C3C"), .fg = s("#c6d0f5") };
c("StatusLine");
c("NormalFloat");
c("NvimTreeNormal");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#EEBEBE") };
c("@event");
c("@symbol");
c("@modifier");
c("@decorator");
c("@interface");
c("Identifier");
c("@enumMember");
c("rainbowcol6");
c("@symbol.ruby");
c("markdownCode");
c("@constructor.lua");
c("markdownCodeBlock");
c("CmpItemKindVariable");
c("NvimTreeSpecialFile");
c("TelescopeSelectionCaret");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#E5C890"), .italic = True };
c("DashboardFooter");
c("LspDiagnosticsVirtualTextWarning");
api_free_keydict_highlight(&o);
h("ColorColumn", .bg = s("#414559"));
h("TelescopeSelection", .bg = s("#414559"), .bold = True, .fg = s("#c6d0f5"));
o = (KeyDict_highlight){ .bg = s("#51576d") };
c("PmenuSbar");
c("illuminatedWord");
c("LspReferenceText");
c("LspReferenceRead");
c("LspReferenceWrite");
c("illuminatedCurWord");
api_free_keydict_highlight(&o);
h("TabLineSel", .bg = s("#51576d"), .fg = s("#A6D189"));
o = (KeyDict_highlight){ .fg = s("#838ba7") };
c("Conceal");
c("@text.todo.unchecked");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("PreProc") };
c("Define");
c("@preproc");
c("PreCondit");
api_free_keydict_highlight(&o);
h("@define", .link = s("Define"));
h("@operator", .link = s("Operator"));
h("Comment", .fg = s("#626880"));
o = (KeyDict_highlight){ .fg = s("#949cbb") };
c("CmpItemAbbr");
c("@punctuation.bracket");
c("@punctuation.delimiter");
api_free_keydict_highlight(&o);
h("IndentBlanklineChar", .fg = s("#414559"));
h("DiffChange", .bg = s("#363C52"));
h("IndentBlanklineContextStart", .sp = s("#c6d0f5"), .underline = True);
o = (KeyDict_highlight){ .fg = s("#85C1DC") };
c("Label");
c("@constructor");
api_free_keydict_highlight(&o);
h("@boolean", .link = s("Boolean"));
o = (KeyDict_highlight){ .link = s("Number") };
c("@float");
c("@number");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Function") };
c("@function");
c("@method.php");
c("@method.call.php");
api_free_keydict_highlight(&o);
h("@function.call", .link = s("@function"));
h("@method.call", .link = s("@method"));
h("@text.strong", .bold = True, .fg = s("#EA999C"));
h("debugPC", .bg = s("#232634"));
h("@text.strike", .fg = s("#c6d0f5"), .strikethrough = True);
o = (KeyDict_highlight){ .link = s("Keyword") };
c("@keyword");
c("@type.qualifier.php");
api_free_keydict_highlight(&o);
h("@text.uri", .fg = s("#F2D5CF"), .italic = True, .underline = True);
h("@conditional", .link = s("Conditional"));
h("@repeat", .link = s("Repeat"));
o = (KeyDict_highlight){ .bg = s("#E5C890"), .fg = s("#303446") };
c("@text.todo");
c("@text.warning");
api_free_keydict_highlight(&o);
h("@include", .link = s("Include"));
h("@text.note", .bg = s("#8CAAEE"), .fg = s("#303446"));
o = (KeyDict_highlight){ .link = s("@type") };
c("@type.qualifier");
c("@type.definition");
api_free_keydict_highlight(&o);
h("@storageclass", .link = s("StorageClass"));
h("@attribute", .link = s("Constant"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#EEBEBE") };
c("mkdCodeEnd");
c("mkdCodeStart");
api_free_keydict_highlight(&o);
h("@constant.macro", .link = s("Macro"));
o = (KeyDict_highlight){ .bg = s("#737994") };
c("WildMenu");
c("PmenuThumb");
api_free_keydict_highlight(&o);
h("markdownLinkText", .fg = s("#8CAAEE"), .underline = True);
h("VertSplit", .fg = s("#232634"));
h("@text.underline", .link = s("Underline"));
h("Underlined", .underline = True);
h("CurSearch", .bg = s("#E78284"), .fg = s("#292C3C"));
h("DiagnosticInfo", .bg = s("NONE"), .fg = s("#99D1DB"), .italic = True);
h("DiagnosticHint", .bg = s("NONE"), .fg = s("#81C8BE"), .italic = True);
h("PmenuSel", .bg = s("#51576d"), .bold = True, .fg = s("#c6d0f5"));
o = (KeyDict_highlight){ .fg = s("#737994") };
c("NonText");
c("diffLine");
c("FoldColumn");
c("LspCodeLens");
c("NvimTreeIndentMarker");
api_free_keydict_highlight(&o);
h("GitSignsAddPreview", .link = s("DiffAdd"));
h("NvimTreeWinSeparator", .bg = s("#303446"), .fg = s("#303446"));
h("NvimTreeStatuslineNc", .bg = s("#292C3C"), .fg = s("#292C3C"));
o = (KeyDict_highlight){ .fg = s("#51576d") };
c("LineNr");
c("SignColumn");
c("Whitespace");
api_free_keydict_highlight(&o);
h("CursorLine", .bg = s("#3B3F52"));
h("@character.special", .link = s("SpecialChar"));
h("DiagnosticVirtualTextError", .bg = s("#413B4C"), .fg = s("#E78284"), .italic = True);
o = (KeyDict_highlight){ .bg = s("#51576d"), .bold = True };
c("Visual");
c("VisualNOS");
c("QuickFixLine");
api_free_keydict_highlight(&o);
h("@error", .link = s("Error"));
h("DiagnosticVirtualTextWarn", .bg = s("#41424D"), .fg = s("#E5C890"), .italic = True);
h("@string", .link = s("String"));
h("SpellLocal", .sp = s("#8CAAEE"), .undercurl = True);
h("@keyword.export", .bold = True, .fg = s("#99D1DB"));
h("DiagnosticVirtualTextInfo", .bg = s("#3A4354"), .fg = s("#99D1DB"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#BABBF1") };
c("@field");
c("@property");
c("@type.css");
c("markdownH1");
c("CursorLineNr");
c("@property.css");
c("@constructor.tsx");
c("@constructor.typescript");
api_free_keydict_highlight(&o);
h("DiagnosticVirtualTextHint", .bg = s("#384251"), .fg = s("#81C8BE"), .italic = True);
h("@tag.attribute.tsx", .fg = s("#CA9EE6"), .italic = True);
h("@label", .link = s("Label"));
Error_check
}