#include "nvim.h"
int luaopen_catppuccin_compiled_latte(lua_State *lstate) {
	o("termguicolors", True);
	g("colors_name", s("catpussy"));
	Error err = ERROR_INIT;
	KeyDict_highlight o;

o("background", s("light"));
g("terminal_color_2", s("#40A02B"));
g("terminal_color_10", s("#40A02B"));
g("terminal_color_3", s("#df8e1d"));
g("terminal_color_11", s("#df8e1d"));
g("terminal_color_4", s("#1e66f5"));
g("terminal_color_12", s("#1e66f5"));
g("terminal_color_5", s("#ea76cb"));
g("terminal_color_13", s("#ea76cb"));
g("terminal_color_6", s("#04A5E5"));
g("terminal_color_14", s("#04A5E5"));
g("terminal_color_7", s("#4C4F69"));
g("terminal_color_15", s("#4C4F69"));
g("terminal_color_0", s("#9CA0B0"));
g("terminal_color_8", s("#8C8FA1"));
g("terminal_color_1", s("#D20F39"));
g("terminal_color_9", s("#D20F39"));
h("GitSignsDeletePreview", .link = s("DiffDelete"));
o = (KeyDict_highlight){ .sp = s("#D20F39"), .underline = True };
c("DiagnosticUnderlineError");
c("LspDiagnosticsUnderlineError");
api_free_keydict_highlight(&o);
h("Todo", .bg = s("#df8e1d"), .bold = True, .fg = s("#EFF1F5"));
o = (KeyDict_highlight){ .bg = s("#9CA0B0") };
c("WildMenu");
c("PmenuThumb");
api_free_keydict_highlight(&o);
h("DiffDelete", .bg = s("#EAC8D3"));
h("VertSplit", .fg = s("#DCE0E8"));
h("Substitute", .bg = s("#BCC0CC"), .fg = s("#D20F39"));
h("Folded", .bg = s("#BCC0CC"), .fg = s("#1e66f5"));
h("SpellRare", .sp = s("#40A02B"), .undercurl = True);
h("SpellCap", .sp = s("#df8e1d"), .undercurl = True);
h("markdownLinkText", .fg = s("#1e66f5"), .underline = True);
o = (KeyDict_highlight){ .bold = True, .fg = s("#4C4F69") };
c("ModeMsg");
c("CmpItemAbbrMatch");
c("CmpItemAbbrMatchFuzzy");
api_free_keydict_highlight(&o);
h("@character", .link = s("Character"));
h("Search", .bg = s("#A8DAF0"), .fg = s("#4C4F69"));
h("Pmenu", .bg = s("#CFD3DD"), .fg = s("#7C7F93"));
h("NormalSB", .bg = s("#DCE0E8"), .fg = s("#4C4F69"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#FE640B") };
c("MatchParen");
c("markdownHeadingDelimiter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#40A02B") };
c("String");
c("diffAdded");
c("markdownH3");
c("GitSignsAdd");
c("rainbowcol7");
c("TSRainbowGreen");
c("CmpItemKindUnit");
c("DashboardCenter");
c("CmpItemKindEnum");
c("CmpItemKindField");
c("@text.todo.checked");
c("CmpItemKindProperty");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#1e66f5") };
c("@class");
c("MoreMsg");
c("@struct");
c("Question");
c("Function");
c("diffFile");
c("Directory");
c("@text.math");
c("qfFileName");
c("FloatBorder");
c("@label.json");
c("@field.yaml");
c("CmpItemKind");
c("rainbowcol4");
c("diffChanged");
c("TSRainbowBlue");
c("LspInfoBorder");
c("GlyphPalette4");
c("NvimTreeGitNew");
c("@property.toml");
c("CmpItemKindFile");
c("@string.special");
c("TelescopeBorder");
c("DashboardHeader");
c("CmpItemKindEvent");
c("@property.id.css");
c("CmpItemKindModule");
c("CmpItemKindFolder");
c("CmpItemKindMethod");
c("CmpItemKindStruct");
c("TelescopeMatching");
c("NvimTreeFolderName");
c("NvimTreeFolderIcon");
c("CmpItemKindOperator");
c("CmpItemKindFunction");
c("@text.environment.name");
c("CmpItemKindConstructor");
c("NvimTreeEmptyFolderName");
c("CmpItemKindTypeParameter");
c("NvimTreeOpenedFolderName");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#1e66f5") };
c("Title");
c("htmlH2");
c("@text.title");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#FE640B") };
c("Float");
c("Number");
c("Boolean");
c("@method");
c("Constant");
c("@constant");
c("diffNewFile");
c("@number.css");
c("@string.regex");
c("TSRainbowOrange");
c("CmpItemKindValue");
c("@constant.builtin");
c("@function.builtin");
c("@string.plain.css");
c("CmpItemKindConstant");
c("LspSignatureActiveParameter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#8839EF") };
c("@tag");
c("Macro");
c("Repeat");
c("Keyword");
c("Include");
c("Statement");
c("markdownH2");
c("@exception");
c("Conditional");
c("@type.tag.css");
c("@keyword.return");
c("TSRainbowViolet");
c("@keyword.function");
c("@keyword.operator");
c("CmpItemKindSnippet");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#179299") };
c("@enum");
c("Character");
c("markdownH6");
c("rainbowcol2");
c("diffIndexLine");
c("healthSuccess");
c("TSRainbowCyan");
c("GlyphPalette6");
c("@text.literal");
c("GlyphPalette2");
c("CmpItemKindText");
c("@function.macro");
c("LspDiagnosticsHint");
c("DiagnosticSignHint");
c("CmpItemKindCopilot");
c("DiagnosticFloatingHint");
c("LspDiagnosticsDefaultHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#D20F39") };
c("Error");
c("rainbowcol1");
c("diffRemoved");
c("healthError");
c("TSRainbowRed");
c("GlyphPalette9");
c("GlyphPalette1");
c("GitSignsDelete");
c("CmpItemKindColor");
c("@variable.builtin");
c("CmpItemKindKeyword");
c("NvimTreeGitDeleted");
c("LspDiagnosticsError");
c("DiagnosticSignError");
c("CmpItemKindReference");
c("CmpItemKindEnumMember");
c("DiagnosticFloatingError");
c("LspDiagnosticsDefaultError");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#df8e1d") };
c("Type");
c("qfLineNr");
c("Structure");
c("WarningMsg");
c("markdownH4");
c("diffOldFile");
c("rainbowcol3");
c("StorageClass");
c("healthWarning");
c("GlyphPalette3");
c("@type.builtin");
c("GitSignsChange");
c("@typeParameter");
c("TSRainbowYellow");
c("CmpItemKindClass");
c("NvimTreeGitDirty");
c("DiagnosticSignWarn");
c("@property.class.css");
c("CmpItemKindInterface");
c("LspDiagnosticsWarning");
c("DiagnosticFloatingWarn");
c("LspDiagnosticsDefaultWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#ea76cb") };
c("Special");
c("PreProc");
c("@regexp");
c("markdownH5");
c("rainbowcol5");
c("@string.escape");
c("NvimTreeSymlink");
c("@text.environment");
c("DashboardShortCut");
c("NvimTreeOpenedFile");
api_free_keydict_highlight(&o);
h("DiagnosticWarn", .bg = s("NONE"), .fg = s("#df8e1d"), .italic = True);
h("DiagnosticError", .bg = s("NONE"), .fg = s("#D20F39"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#04A5E5") };
c("Operator");
c("@tag.delimiter");
c("DiagnosticSignInfo");
c("@punctuation.special");
c("DiagnosticFloatingInfo");
c("LspDiagnosticsInformation");
c("LspDiagnosticsDefaultInformation");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#CBCFD8") };
c("IlluminatedWordText");
c("IlluminatedWordRead");
c("IlluminatedWordWrite");
api_free_keydict_highlight(&o);
h("CursorColumn", .bg = s("#E6E9EF"));
o = (KeyDict_highlight){ .fg = s("#4C4F69") };
c("@text");
c("@variable");
c("SpecialKey");
c("CmpItemMenu");
c("GlyphPalette7");
c("NvimTreeImageFile");
c("IndentBlanklineContextChar");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#E6E9EF"), .fg = s("#4C4F69") };
c("StatusLine");
c("NormalFloat");
c("NvimTreeNormal");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#DD7878") };
c("@event");
c("@symbol");
c("@modifier");
c("@decorator");
c("@interface");
c("Identifier");
c("@enumMember");
c("rainbowcol6");
c("@symbol.ruby");
c("markdownCode");
c("@constructor.lua");
c("markdownCodeBlock");
c("CmpItemKindVariable");
c("NvimTreeSpecialFile");
c("TelescopeSelectionCaret");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#df8e1d"), .italic = True };
c("DashboardFooter");
c("LspDiagnosticsVirtualTextWarning");
api_free_keydict_highlight(&o);
h("ColorColumn", .bg = s("#CCD0DA"));
h("TelescopeSelection", .bg = s("#CCD0DA"), .bold = True, .fg = s("#4C4F69"));
o = (KeyDict_highlight){ .bg = s("#BCC0CC") };
c("PmenuSbar");
c("illuminatedWord");
c("LspReferenceText");
c("LspReferenceRead");
c("LspReferenceWrite");
c("illuminatedCurWord");
api_free_keydict_highlight(&o);
h("TabLineSel", .bg = s("#BCC0CC"), .fg = s("#40A02B"));
o = (KeyDict_highlight){ .fg = s("#8C8FA1") };
c("Conceal");
c("@text.todo.unchecked");
api_free_keydict_highlight(&o);
h("SignColumnSB", .bg = s("#DCE0E8"), .fg = s("#BCC0CC"));
h("EndOfBuffer", .fg = s("#EFF1F5"));
o = (KeyDict_highlight){ .bg = s("#4C4F69"), .fg = s("#EFF1F5") };
c("Cursor");
c("lCursor");
c("CursorIM");
api_free_keydict_highlight(&o);
h("Comment", .fg = s("#ACB0BE"));
o = (KeyDict_highlight){ .fg = s("#7C7F93") };
c("CmpItemAbbr");
c("@punctuation.bracket");
c("@punctuation.delimiter");
api_free_keydict_highlight(&o);
h("IndentBlanklineChar", .fg = s("#CCD0DA"));
o = (KeyDict_highlight){ .sp = s("#df8e1d"), .underline = True };
c("DiagnosticUnderlineWarn");
c("LspDiagnosticsUnderlineWarning");
api_free_keydict_highlight(&o);
h("IndentBlanklineContextStart", .sp = s("#4C4F69"), .underline = True);
o = (KeyDict_highlight){ .fg = s("#209FB5") };
c("Label");
c("@constructor");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#E6E9EF"), .fg = s("#BCC0CC") };
c("TabLine");
c("StatusLineNC");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#E64553"), .italic = True };
c("@parameter");
c("@text.emphasis");
api_free_keydict_highlight(&o);
h("@keyword.export", .bold = True, .fg = s("#04A5E5"));
o = (KeyDict_highlight){ .fg = s("#7287FD") };
c("@field");
c("@property");
c("@type.css");
c("markdownH1");
c("CursorLineNr");
c("@property.css");
c("@constructor.tsx");
c("@constructor.typescript");
api_free_keydict_highlight(&o);
h("@namespace", .fg = s("#7287FD"), .italic = True);
h("@text.strong", .bold = True, .fg = s("#E64553"));
h("debugPC", .bg = s("#DCE0E8"));
h("@text.strike", .fg = s("#4C4F69"), .strikethrough = True);
o = (KeyDict_highlight){ .fg = s("#dc8a78") };
c("WinBar");
c("@property.cpp");
api_free_keydict_highlight(&o);
h("@text.uri", .fg = s("#dc8a78"), .italic = True, .underline = True);
o = (KeyDict_highlight){ .bold = True, .fg = s("#7287FD") };
c("@text.reference");
c("NvimTreeRootFolder");
api_free_keydict_highlight(&o);
h("@character.special", .link = s("SpecialChar"));
o = (KeyDict_highlight){ .bg = s("#df8e1d"), .fg = s("#EFF1F5") };
c("@text.todo");
c("@text.warning");
api_free_keydict_highlight(&o);
h("ErrorMsg", .bold = True, .fg = s("#D20F39"), .italic = True);
h("@text.note", .bg = s("#1e66f5"), .fg = s("#EFF1F5"));
o = (KeyDict_highlight){ .bg = s("#EFF1F5"), .fg = s("#4C4F69") };
c("Normal");
c("NormalNC");
c("mkdCodeDelimiter");
api_free_keydict_highlight(&o);
h("@text.danger", .bg = s("#D20F39"), .fg = s("#EFF1F5"));
h("@comment", .link = s("Comment"));
h("@error", .link = s("Error"));
o = (KeyDict_highlight){ .link = s("PreProc") };
c("Define");
c("@preproc");
c("PreCondit");
api_free_keydict_highlight(&o);
h("@define", .link = s("Define"));
h("@operator", .link = s("Operator"));
o = (KeyDict_highlight){ .sp = s("#179299"), .underline = True };
c("DiagnosticUnderlineHint");
c("LspDiagnosticsUnderlineHint");
api_free_keydict_highlight(&o);
h("@string", .link = s("String"));
h("LspDiagnosticsVirtualTextInformation", .fg = s("#04A5E5"), .italic = True);
h("LspDiagnosticsVirtualTextError", .fg = s("#D20F39"), .italic = True);
h("Underlined", .underline = True);
h("CmpItemAbbrDeprecated", .fg = s("#9CA0B0"), .strikethrough = True);
h("@boolean", .link = s("Boolean"));
o = (KeyDict_highlight){ .link = s("Number") };
c("@float");
c("@number");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Function") };
c("@function");
c("@method.php");
c("@method.call.php");
api_free_keydict_highlight(&o);
h("@function.call", .link = s("@function"));
h("@method.call", .link = s("@method"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#DD7878") };
c("mkdCodeEnd");
c("mkdCodeStart");
api_free_keydict_highlight(&o);
h("@text.diff.add", .link = s("diffAdded"));
h("@text.diff.delete", .link = s("diffRemoved"));
o = (KeyDict_highlight){ .link = s("Keyword") };
c("@keyword");
c("@type.qualifier.php");
api_free_keydict_highlight(&o);
h("GitSignsAddPreview", .link = s("DiffAdd"));
h("@conditional", .link = s("Conditional"));
h("@repeat", .link = s("Repeat"));
h("@label", .link = s("Label"));
h("@include", .link = s("Include"));
o = (KeyDict_highlight){ .link = s("Type") };
c("@type");
c("Typedef");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("@type") };
c("@type.qualifier");
c("@type.definition");
api_free_keydict_highlight(&o);
h("@storageclass", .link = s("StorageClass"));
h("@attribute", .link = s("Constant"));
h("DiffChange", .bg = s("#E0E7F5"));
h("@constant.macro", .link = s("Macro"));
h("CurSearch", .bg = s("#D20F39"), .fg = s("#E6E9EF"));
h("DiagnosticInfo", .bg = s("NONE"), .fg = s("#04A5E5"), .italic = True);
h("DiagnosticHint", .bg = s("NONE"), .fg = s("#179299"), .italic = True);
h("@text.underline", .link = s("Underline"));
o = (KeyDict_highlight){ .fg = s("#9CA0B0") };
c("NonText");
c("diffLine");
c("FoldColumn");
c("LspCodeLens");
c("NvimTreeIndentMarker");
api_free_keydict_highlight(&o);
h("htmlH1", .bold = True, .fg = s("#ea76cb"));
h("NvimTreeWinSeparator", .bg = s("#EFF1F5"), .fg = s("#EFF1F5"));
h("NvimTreeStatuslineNc", .bg = s("#E6E9EF"), .fg = s("#E6E9EF"));
o = (KeyDict_highlight){ .fg = s("#BCC0CC") };
c("LineNr");
c("SignColumn");
c("Whitespace");
api_free_keydict_highlight(&o);
h("CursorLine", .bg = s("#E9EBF1"));
h("IncSearch", .bg = s("#1BADE7"), .fg = s("#E6E9EF"));
h("DiagnosticVirtualTextError", .bg = s("#ECDCE3"), .fg = s("#D20F39"), .italic = True);
o = (KeyDict_highlight){ .bg = s("#BCC0CC"), .bold = True };
c("Visual");
c("VisualNOS");
c("QuickFixLine");
api_free_keydict_highlight(&o);
h("SpellBad", .sp = s("#D20F39"), .undercurl = True);
h("DiagnosticVirtualTextWarn", .bg = s("#EDE8E0"), .fg = s("#df8e1d"), .italic = True);
h("PmenuSel", .bg = s("#BCC0CC"), .bold = True, .fg = s("#4C4F69"));
h("SpellLocal", .sp = s("#1e66f5"), .undercurl = True);
h("DiffAdd", .bg = s("#D0E2D1"));
h("DiagnosticVirtualTextInfo", .bg = s("#D9EAF3"), .fg = s("#04A5E5"), .italic = True);
h("debugBreakpoint", .bg = s("#EFF1F5"), .fg = s("#9CA0B0"));
h("DiagnosticVirtualTextHint", .bg = s("#DAE8EC"), .fg = s("#179299"), .italic = True);
h("@tag.attribute.tsx", .fg = s("#8839EF"), .italic = True);
h("DiffText", .bg = s("#C9D8F5"));
o = (KeyDict_highlight){ .sp = s("#04A5E5"), .underline = True };
c("DiagnosticUnderlineInfo");
c("LspDiagnosticsUnderlineInformation");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#179299"), .italic = True };
c("@tag.attribute");
c("LspDiagnosticsVirtualTextHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Special") };
c("Tag");
c("Debug");
c("Delimiter");
c("SpecialChar");
c("SpecialComment");
api_free_keydict_highlight(&o);
h("Bold", .bold = True);
h("Italic", .italic = True);
Error_check
}