#include "nvim.h"
int luaopen_catppuccin_compiled_macchiato(lua_State *lstate) {
	o("termguicolors", True);
	g("colors_name", s("catpussy"));
	Error err = ERROR_INIT;
	KeyDict_highlight o;

o("background", s("dark"));
g("terminal_color_2", s("#A6DA95"));
g("terminal_color_10", s("#A6DA95"));
g("terminal_color_3", s("#EED49F"));
g("terminal_color_11", s("#EED49F"));
g("terminal_color_4", s("#8AADF4"));
g("terminal_color_12", s("#8AADF4"));
g("terminal_color_5", s("#F5BDE6"));
g("terminal_color_13", s("#F5BDE6"));
g("terminal_color_6", s("#91D7E3"));
g("terminal_color_14", s("#91D7E3"));
g("terminal_color_7", s("#CAD3F5"));
g("terminal_color_15", s("#CAD3F5"));
g("terminal_color_0", s("#6E738D"));
g("terminal_color_8", s("#8087A2"));
g("terminal_color_1", s("#ED8796"));
g("terminal_color_9", s("#ED8796"));
o = (KeyDict_highlight){ .sp = s("#EED49F"), .underline = True };
c("DiagnosticUnderlineWarn");
c("LspDiagnosticsUnderlineWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .sp = s("#8BD5CA"), .underline = True };
c("DiagnosticUnderlineHint");
c("LspDiagnosticsUnderlineHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#1E2030"), .fg = s("#494D64") };
c("TabLine");
c("StatusLineNC");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#24273A"), .fg = s("#CAD3F5") };
c("Normal");
c("NormalNC");
c("mkdCodeDelimiter");
api_free_keydict_highlight(&o);
h("ErrorMsg", .bold = True, .fg = s("#ED8796"), .italic = True);
h("Folded", .bg = s("#494D64"), .fg = s("#8AADF4"));
h("SignColumnSB", .bg = s("#181926"), .fg = s("#494D64"));
h("Substitute", .bg = s("#494D64"), .fg = s("#F5BDE6"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#F5A97F") };
c("MatchParen");
c("markdownHeadingDelimiter");
api_free_keydict_highlight(&o);
h("NormalSB", .bg = s("#181926"), .fg = s("#CAD3F5"));
h("Pmenu", .bg = s("#303347"), .fg = s("#939AB7"));
h("Search", .bg = s("#455C6D"), .fg = s("#CAD3F5"));
h("IncSearch", .bg = s("#86C5D2"), .fg = s("#1E2030"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#CAD3F5") };
c("ModeMsg");
c("CmpItemAbbrMatch");
c("CmpItemAbbrMatchFuzzy");
api_free_keydict_highlight(&o);
h("PmenuSel", .bg = s("#494D64"), .bold = True, .fg = s("#CAD3F5"));
h("SpellBad", .sp = s("#ED8796"), .undercurl = True);
h("SpellCap", .sp = s("#EED49F"), .undercurl = True);
h("GitSignsDeletePreview", .link = s("DiffDelete"));
h("SpellRare", .sp = s("#A6DA95"), .undercurl = True);
h("DiffAdd", .bg = s("#3B474A"));
h("DiffDelete", .bg = s("#48384B"));
h("debugBreakpoint", .bg = s("#24273A"), .fg = s("#6E738D"));
h("Todo", .bg = s("#EED49F"), .bold = True, .fg = s("#24273A"));
o = (KeyDict_highlight){ .sp = s("#ED8796"), .underline = True };
c("DiagnosticUnderlineError");
c("LspDiagnosticsUnderlineError");
api_free_keydict_highlight(&o);
h("DiffText", .bg = s("#363F5B"));
h("DiagnosticHint", .bg = s("NONE"), .fg = s("#8BD5CA"), .italic = True);
o = (KeyDict_highlight){ .link = s("Number") };
c("@float");
c("@number");
api_free_keydict_highlight(&o);
h("@function.call", .link = s("@function"));
h("@text.strike", .fg = s("#CAD3F5"), .strikethrough = True);
h("@text.danger", .bg = s("#ED8796"), .fg = s("#24273A"));
o = (KeyDict_highlight){ .fg = s("#8BD5CA"), .italic = True };
c("@tag.attribute");
c("LspDiagnosticsVirtualTextHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#A6DA95") };
c("String");
c("diffAdded");
c("markdownH3");
c("GitSignsAdd");
c("rainbowcol7");
c("TSRainbowGreen");
c("CmpItemKindUnit");
c("DashboardCenter");
c("CmpItemKindEnum");
c("CmpItemKindField");
c("@text.todo.checked");
c("CmpItemKindProperty");
api_free_keydict_highlight(&o);
h("Bold", .bold = True);
o = (KeyDict_highlight){ .fg = s("#8AADF4") };
c("@class");
c("MoreMsg");
c("@struct");
c("Question");
c("Function");
c("diffFile");
c("Directory");
c("@text.math");
c("qfFileName");
c("FloatBorder");
c("@label.json");
c("@field.yaml");
c("CmpItemKind");
c("rainbowcol4");
c("diffChanged");
c("TSRainbowBlue");
c("LspInfoBorder");
c("GlyphPalette4");
c("NvimTreeGitNew");
c("@property.toml");
c("CmpItemKindFile");
c("@string.special");
c("TelescopeBorder");
c("DashboardHeader");
c("CmpItemKindEvent");
c("@property.id.css");
c("CmpItemKindModule");
c("CmpItemKindFolder");
c("CmpItemKindMethod");
c("CmpItemKindStruct");
c("TelescopeMatching");
c("NvimTreeFolderName");
c("NvimTreeFolderIcon");
c("CmpItemKindOperator");
c("CmpItemKindFunction");
c("@text.environment.name");
c("CmpItemKindConstructor");
c("NvimTreeEmptyFolderName");
c("CmpItemKindTypeParameter");
c("NvimTreeOpenedFolderName");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#8AADF4") };
c("Title");
c("htmlH2");
c("@text.title");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F5A97F") };
c("Float");
c("Number");
c("Boolean");
c("@method");
c("Constant");
c("@constant");
c("diffNewFile");
c("@number.css");
c("@string.regex");
c("TSRainbowOrange");
c("CmpItemKindValue");
c("@constant.builtin");
c("@function.builtin");
c("@string.plain.css");
c("CmpItemKindConstant");
c("LspSignatureActiveParameter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#C6A0F6") };
c("@tag");
c("Macro");
c("Repeat");
c("Keyword");
c("Include");
c("Statement");
c("markdownH2");
c("@exception");
c("Conditional");
c("@type.tag.css");
c("@keyword.return");
c("TSRainbowViolet");
c("@keyword.function");
c("@keyword.operator");
c("CmpItemKindSnippet");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#8BD5CA") };
c("@enum");
c("Character");
c("markdownH6");
c("rainbowcol2");
c("diffIndexLine");
c("healthSuccess");
c("TSRainbowCyan");
c("GlyphPalette6");
c("@text.literal");
c("GlyphPalette2");
c("CmpItemKindText");
c("@function.macro");
c("LspDiagnosticsHint");
c("DiagnosticSignHint");
c("CmpItemKindCopilot");
c("DiagnosticFloatingHint");
c("LspDiagnosticsDefaultHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#ED8796") };
c("Error");
c("rainbowcol1");
c("diffRemoved");
c("healthError");
c("TSRainbowRed");
c("GlyphPalette9");
c("GlyphPalette1");
c("GitSignsDelete");
c("CmpItemKindColor");
c("@variable.builtin");
c("CmpItemKindKeyword");
c("NvimTreeGitDeleted");
c("LspDiagnosticsError");
c("DiagnosticSignError");
c("CmpItemKindReference");
c("CmpItemKindEnumMember");
c("DiagnosticFloatingError");
c("LspDiagnosticsDefaultError");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#EED49F") };
c("Type");
c("qfLineNr");
c("Structure");
c("WarningMsg");
c("markdownH4");
c("diffOldFile");
c("rainbowcol3");
c("StorageClass");
c("healthWarning");
c("GlyphPalette3");
c("@type.builtin");
c("GitSignsChange");
c("@typeParameter");
c("TSRainbowYellow");
c("CmpItemKindClass");
c("NvimTreeGitDirty");
c("DiagnosticSignWarn");
c("@property.class.css");
c("CmpItemKindInterface");
c("LspDiagnosticsWarning");
c("DiagnosticFloatingWarn");
c("LspDiagnosticsDefaultWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F5BDE6") };
c("Special");
c("PreProc");
c("@regexp");
c("markdownH5");
c("rainbowcol5");
c("@string.escape");
c("NvimTreeSymlink");
c("@text.environment");
c("DashboardShortCut");
c("NvimTreeOpenedFile");
api_free_keydict_highlight(&o);
h("GitSignsAddPreview", .link = s("DiffAdd"));
h("Italic", .italic = True);
h("DiagnosticWarn", .bg = s("NONE"), .fg = s("#EED49F"), .italic = True);
h("DiagnosticError", .bg = s("NONE"), .fg = s("#ED8796"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#91D7E3") };
c("Operator");
c("@tag.delimiter");
c("DiagnosticSignInfo");
c("@punctuation.special");
c("DiagnosticFloatingInfo");
c("LspDiagnosticsInformation");
c("LspDiagnosticsDefaultInformation");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#3E4257") };
c("IlluminatedWordText");
c("IlluminatedWordRead");
c("IlluminatedWordWrite");
api_free_keydict_highlight(&o);
h("CursorColumn", .bg = s("#1E2030"));
o = (KeyDict_highlight){ .fg = s("#CAD3F5") };
c("@text");
c("@variable");
c("SpecialKey");
c("CmpItemMenu");
c("GlyphPalette7");
c("NvimTreeImageFile");
c("IndentBlanklineContextChar");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#1E2030"), .fg = s("#CAD3F5") };
c("StatusLine");
c("NormalFloat");
c("NvimTreeNormal");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F0C6C6") };
c("@event");
c("@symbol");
c("@modifier");
c("@decorator");
c("@interface");
c("Identifier");
c("@enumMember");
c("rainbowcol6");
c("@symbol.ruby");
c("markdownCode");
c("@constructor.lua");
c("markdownCodeBlock");
c("CmpItemKindVariable");
c("NvimTreeSpecialFile");
c("TelescopeSelectionCaret");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#EED49F"), .italic = True };
c("DashboardFooter");
c("LspDiagnosticsVirtualTextWarning");
api_free_keydict_highlight(&o);
h("ColorColumn", .bg = s("#363A4F"));
h("TelescopeSelection", .bg = s("#363A4F"), .bold = True, .fg = s("#CAD3F5"));
o = (KeyDict_highlight){ .bg = s("#494D64") };
c("PmenuSbar");
c("illuminatedWord");
c("LspReferenceText");
c("LspReferenceRead");
c("LspReferenceWrite");
c("illuminatedCurWord");
api_free_keydict_highlight(&o);
h("TabLineSel", .bg = s("#494D64"), .fg = s("#A6DA95"));
h("@character", .link = s("Character"));
h("VertSplit", .fg = s("#181926"));
h("Underlined", .underline = True);
o = (KeyDict_highlight){ .link = s("Special") };
c("Tag");
c("Debug");
c("Delimiter");
c("SpecialChar");
c("SpecialComment");
api_free_keydict_highlight(&o);
h("@character.special", .link = s("SpecialChar"));
o = (KeyDict_highlight){ .fg = s("#8087A2") };
c("Conceal");
c("@text.todo.unchecked");
api_free_keydict_highlight(&o);
h("CurSearch", .bg = s("#ED8796"), .fg = s("#1E2030"));
h("EndOfBuffer", .fg = s("#24273A"));
o = (KeyDict_highlight){ .bg = s("#CAD3F5"), .fg = s("#24273A") };
c("Cursor");
c("lCursor");
c("CursorIM");
api_free_keydict_highlight(&o);
h("Comment", .fg = s("#5B6078"));
h("@comment", .link = s("Comment"));
h("@error", .link = s("Error"));
o = (KeyDict_highlight){ .link = s("PreProc") };
c("Define");
c("@preproc");
c("PreCondit");
api_free_keydict_highlight(&o);
h("@define", .link = s("Define"));
h("@operator", .link = s("Operator"));
o = (KeyDict_highlight){ .fg = s("#939AB7") };
c("CmpItemAbbr");
c("@punctuation.bracket");
c("@punctuation.delimiter");
api_free_keydict_highlight(&o);
h("@string", .link = s("String"));
h("IndentBlanklineChar", .fg = s("#363A4F"));
o = (KeyDict_highlight){ .fg = s("#F4DBD6") };
c("WinBar");
c("@property.cpp");
api_free_keydict_highlight(&o);
h("@text.uri", .fg = s("#F4DBD6"), .italic = True, .underline = True);
o = (KeyDict_highlight){ .bold = True, .fg = s("#B7BDF8") };
c("@text.reference");
c("NvimTreeRootFolder");
api_free_keydict_highlight(&o);
h("@boolean", .link = s("Boolean"));
o = (KeyDict_highlight){ .bg = s("#EED49F"), .fg = s("#24273A") };
c("@text.todo");
c("@text.warning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Function") };
c("@function");
c("@method.php");
c("@method.call.php");
api_free_keydict_highlight(&o);
h("@text.note", .bg = s("#8AADF4"), .fg = s("#24273A"));
h("@method.call", .link = s("@method"));
o = (KeyDict_highlight){ .fg = s("#7DC4E4") };
c("Label");
c("@constructor");
api_free_keydict_highlight(&o);
h("@text.diff.add", .link = s("diffAdded"));
o = (KeyDict_highlight){ .fg = s("#EE99A0"), .italic = True };
c("@parameter");
c("@text.emphasis");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Keyword") };
c("@keyword");
c("@type.qualifier.php");
api_free_keydict_highlight(&o);
h("@keyword.export", .bold = True, .fg = s("#91D7E3"));
h("@conditional", .link = s("Conditional"));
h("@repeat", .link = s("Repeat"));
h("@label", .link = s("Label"));
h("@include", .link = s("Include"));
o = (KeyDict_highlight){ .link = s("Type") };
c("@type");
c("Typedef");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("@type") };
c("@type.qualifier");
c("@type.definition");
api_free_keydict_highlight(&o);
h("@storageclass", .link = s("StorageClass"));
h("@attribute", .link = s("Constant"));
o = (KeyDict_highlight){ .fg = s("#B7BDF8") };
c("@field");
c("@property");
c("@type.css");
c("markdownH1");
c("CursorLineNr");
c("@property.css");
c("@constructor.tsx");
c("@constructor.typescript");
api_free_keydict_highlight(&o);
h("@constant.macro", .link = s("Macro"));
h("@namespace", .fg = s("#B7BDF8"), .italic = True);
h("@text.strong", .bold = True, .fg = s("#EE99A0"));
h("debugPC", .bg = s("#181926"));
h("@text.underline", .link = s("Underline"));
o = (KeyDict_highlight){ .fg = s("#6E738D") };
c("NonText");
c("diffLine");
c("FoldColumn");
c("LspCodeLens");
c("NvimTreeIndentMarker");
api_free_keydict_highlight(&o);
h("NvimTreeWinSeparator", .bg = s("#24273A"), .fg = s("#24273A"));
h("NvimTreeStatuslineNc", .bg = s("#1E2030"), .fg = s("#1E2030"));
o = (KeyDict_highlight){ .fg = s("#494D64") };
c("LineNr");
c("SignColumn");
c("Whitespace");
api_free_keydict_highlight(&o);
h("CursorLine", .bg = s("#303347"));
h("DiagnosticInfo", .bg = s("NONE"), .fg = s("#91D7E3"), .italic = True);
h("DiagnosticVirtualTextError", .bg = s("#373043"), .fg = s("#ED8796"), .italic = True);
o = (KeyDict_highlight){ .bg = s("#494D64"), .bold = True };
c("Visual");
c("VisualNOS");
c("QuickFixLine");
api_free_keydict_highlight(&o);
h("DiffChange", .bg = s("#2B3047"));
h("DiagnosticVirtualTextWarn", .bg = s("#373744"), .fg = s("#EED49F"), .italic = True);
h("markdownLinkText", .fg = s("#8AADF4"), .underline = True);
o = (KeyDict_highlight){ .bg = s("#6E738D") };
c("WildMenu");
c("PmenuThumb");
api_free_keydict_highlight(&o);
h("SpellLocal", .sp = s("#8AADF4"), .undercurl = True);
h("htmlH1", .bold = True, .fg = s("#F5BDE6"));
h("DiagnosticVirtualTextInfo", .bg = s("#2E384A"), .fg = s("#91D7E3"), .italic = True);
o = (KeyDict_highlight){ .bold = True, .fg = s("#F0C6C6") };
c("mkdCodeEnd");
c("mkdCodeStart");
api_free_keydict_highlight(&o);
h("DiagnosticVirtualTextHint", .bg = s("#2E3848"), .fg = s("#8BD5CA"), .italic = True);
h("@tag.attribute.tsx", .fg = s("#C6A0F6"), .italic = True);
h("@text.diff.delete", .link = s("diffRemoved"));
o = (KeyDict_highlight){ .sp = s("#91D7E3"), .underline = True };
c("DiagnosticUnderlineInfo");
c("LspDiagnosticsUnderlineInformation");
api_free_keydict_highlight(&o);
h("CmpItemAbbrDeprecated", .fg = s("#6E738D"), .strikethrough = True);
h("LspDiagnosticsVirtualTextError", .fg = s("#ED8796"), .italic = True);
h("LspDiagnosticsVirtualTextInformation", .fg = s("#91D7E3"), .italic = True);
h("IndentBlanklineContextStart", .sp = s("#CAD3F5"), .underline = True);
Error_check
}