#include "nvim.h"
#include <time.h>
int luaopen_catppuccin_compiled_mocha(lua_State *lstate) {
	FILE *fp;
  fp = fopen("/tmp/test.txt", "wb");
	clock_t start = clock();
	o("termguicolors", True);
	g("colors_name", s("catpussy"));
	Error err = ERROR_INIT;
	KeyDict_highlight o;

o("background", s("dark"));
g("terminal_color_2", s("#A6E3A1"));
g("terminal_color_10", s("#A6E3A1"));
g("terminal_color_3", s("#F9E2AF"));
g("terminal_color_11", s("#F9E2AF"));
g("terminal_color_4", s("#89B4FA"));
g("terminal_color_12", s("#89B4FA"));
g("terminal_color_5", s("#F5C2E7"));
g("terminal_color_13", s("#F5C2E7"));
g("terminal_color_6", s("#89DCEB"));
g("terminal_color_14", s("#89DCEB"));
g("terminal_color_7", s("#CDD6F4"));
g("terminal_color_15", s("#CDD6F4"));
g("terminal_color_0", s("#6C7086"));
g("terminal_color_8", s("#7F849C"));
g("terminal_color_1", s("#F38BA8"));
g("terminal_color_9", s("#F38BA8"));
h("GitSignsDeletePreview", .link = s("DiffDelete"));
h("@character", .link = s("Character"));
h("DiffChange", .bg = s("#0A0D12"));
h("DiagnosticInfo", .bg = s("NONE"), .fg = s("#89DCEB"), .italic = True);
h("DiagnosticHint", .bg = s("NONE"), .fg = s("#94E2D5"), .italic = True);
h("PmenuSel", .bg = s("#45475A"), .bold = True, .fg = s("#CDD6F4"));
o = (KeyDict_highlight){ .fg = s("#F5E0DC") };
c("WinBar");
c("@property.cpp");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#6C7086") };
c("NonText");
c("diffLine");
c("FoldColumn");
c("LspCodeLens");
c("NvimTreeIndentMarker");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#45475A") };
c("LineNr");
c("SignColumn");
c("Whitespace");
api_free_keydict_highlight(&o);
h("DiagnosticVirtualTextError", .bg = s("#170D10"), .fg = s("#F38BA8"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#F9E2AF") };
c("Type");
c("qfLineNr");
c("Structure");
c("WarningMsg");
c("markdownH4");
c("diffOldFile");
c("rainbowcol3");
c("StorageClass");
c("healthWarning");
c("GlyphPalette3");
c("@type.builtin");
c("GitSignsChange");
c("@typeParameter");
c("TSRainbowYellow");
c("CmpItemKindClass");
c("NvimTreeGitDirty");
c("DiagnosticSignWarn");
c("@property.class.css");
c("CmpItemKindInterface");
c("LspDiagnosticsWarning");
c("DiagnosticFloatingWarn");
c("LspDiagnosticsDefaultWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F5C2E7") };
c("Special");
c("PreProc");
c("@regexp");
c("markdownH5");
c("rainbowcol5");
c("@string.escape");
c("NvimTreeSymlink");
c("@text.environment");
c("DashboardShortCut");
c("NvimTreeOpenedFile");
api_free_keydict_highlight(&o);
h("DiagnosticWarn", .bg = s("NONE"), .fg = s("#F9E2AF"), .italic = True);
h("DiagnosticError", .bg = s("NONE"), .fg = s("#F38BA8"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#A6E3A1") };
c("String");
c("diffAdded");
c("markdownH3");
c("GitSignsAdd");
c("rainbowcol7");
c("TSRainbowGreen");
c("CmpItemKindUnit");
c("DashboardCenter");
c("CmpItemKindEnum");
c("CmpItemKindField");
c("@text.todo.checked");
c("CmpItemKindProperty");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#30323F") };
c("IlluminatedWordText");
c("IlluminatedWordRead");
c("IlluminatedWordWrite");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#000000") };
c("debugPC");
c("CursorColumn");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#CDD6F4") };
c("@text");
c("@variable");
c("SpecialKey");
c("CmpItemMenu");
c("GlyphPalette7");
c("NvimTreeImageFile");
c("IndentBlanklineContextChar");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#000000"), .fg = s("#CDD6F4") };
c("Normal");
c("NormalNC");
c("NormalSB");
c("StatusLine");
c("NormalFloat");
c("NvimTreeNormal");
c("mkdCodeDelimiter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#94E2D5") };
c("@enum");
c("Character");
c("markdownH6");
c("rainbowcol2");
c("diffIndexLine");
c("healthSuccess");
c("TSRainbowCyan");
c("GlyphPalette6");
c("@text.literal");
c("GlyphPalette2");
c("CmpItemKindText");
c("@function.macro");
c("LspDiagnosticsHint");
c("DiagnosticSignHint");
c("CmpItemKindCopilot");
c("DiagnosticFloatingHint");
c("LspDiagnosticsDefaultHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F38BA8") };
c("Error");
c("rainbowcol1");
c("diffRemoved");
c("healthError");
c("TSRainbowRed");
c("GlyphPalette9");
c("GlyphPalette1");
c("GitSignsDelete");
c("CmpItemKindColor");
c("@variable.builtin");
c("CmpItemKindKeyword");
c("NvimTreeGitDeleted");
c("LspDiagnosticsError");
c("DiagnosticSignError");
c("CmpItemKindReference");
c("CmpItemKindEnumMember");
c("DiagnosticFloatingError");
c("LspDiagnosticsDefaultError");
api_free_keydict_highlight(&o);
h("ColorColumn", .bg = s("#313244"));
h("TelescopeSelection", .bg = s("#313244"), .bold = True, .fg = s("#CDD6F4"));
o = (KeyDict_highlight){ .bg = s("#45475A") };
c("PmenuSbar");
c("illuminatedWord");
c("LspReferenceText");
c("LspReferenceRead");
c("LspReferenceWrite");
c("illuminatedCurWord");
api_free_keydict_highlight(&o);
h("TabLineSel", .bg = s("#45475A"), .fg = s("#A6E3A1"));
h("Bold", .bold = True);
h("DiagnosticVirtualTextWarn", .bg = s("#181511"), .fg = s("#F9E2AF"), .italic = True);
h("SpellLocal", .sp = s("#89B4FA"), .undercurl = True);
o = (KeyDict_highlight){ .fg = s("#7F849C") };
c("Conceal");
c("@text.todo.unchecked");
api_free_keydict_highlight(&o);
h("DiagnosticVirtualTextHint", .bg = s("#0E1514"), .fg = s("#94E2D5"), .italic = True);
o = (KeyDict_highlight){ .fg = s("#000000") };
c("VertSplit");
c("EndOfBuffer");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#CDD6F4"), .fg = s("#000000") };
c("Cursor");
c("lCursor");
c("CursorIM");
api_free_keydict_highlight(&o);
h("Comment", .fg = s("#585B70"));
o = (KeyDict_highlight){ .fg = s("#9399B2") };
c("CmpItemAbbr");
c("@punctuation.bracket");
c("@punctuation.delimiter");
api_free_keydict_highlight(&o);
h("IndentBlanklineChar", .fg = s("#313244"));
h("Italic", .italic = True);
h("IndentBlanklineContextStart", .sp = s("#CDD6F4"), .underline = True);
o = (KeyDict_highlight){ .fg = s("#74C7EC") };
c("Label");
c("@constructor");
api_free_keydict_highlight(&o);
h("Pmenu", .bg = s("#272836"), .fg = s("#9399B2"));
o = (KeyDict_highlight){ .fg = s("#EBA0AC"), .italic = True };
c("@parameter");
c("@text.emphasis");
api_free_keydict_highlight(&o);
h("@keyword.export", .bold = True, .fg = s("#89DCEB"));
o = (KeyDict_highlight){ .fg = s("#B4BEFE") };
c("@field");
c("@property");
c("@type.css");
c("markdownH1");
c("CursorLineNr");
c("@property.css");
c("@constructor.tsx");
c("@constructor.typescript");
api_free_keydict_highlight(&o);
h("@namespace", .fg = s("#B4BEFE"), .italic = True);
h("@text.strong", .bold = True, .fg = s("#EBA0AC"));
h("@text.strike", .fg = s("#CDD6F4"), .strikethrough = True);
h("CursorLine", .bg = s("#1F202C"));
h("@text.uri", .fg = s("#F5E0DC"), .italic = True, .underline = True);
o = (KeyDict_highlight){ .bold = True, .fg = s("#B4BEFE") };
c("@text.reference");
c("NvimTreeRootFolder");
api_free_keydict_highlight(&o);
h("CmpItemAbbrDeprecated", .fg = s("#6C7086"), .strikethrough = True);
o = (KeyDict_highlight){ .bg = s("#F9E2AF"), .fg = s("#000000") };
c("@text.todo");
c("@text.warning");
api_free_keydict_highlight(&o);
h("LspDiagnosticsVirtualTextError", .fg = s("#F38BA8"), .italic = True);
h("@text.note", .bg = s("#89B4FA"), .fg = s("#000000"));
o = (KeyDict_highlight){ .link = s("Special") };
c("Tag");
c("Debug");
c("Delimiter");
c("SpecialChar");
c("SpecialComment");
api_free_keydict_highlight(&o);
h("@character.special", .link = s("SpecialChar"));
o = (KeyDict_highlight){ .fg = s("#94E2D5"), .italic = True };
c("@tag.attribute");
c("LspDiagnosticsVirtualTextHint");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#F2CDCD") };
c("mkdCodeEnd");
c("mkdCodeStart");
api_free_keydict_highlight(&o);
h("htmlH1", .bold = True, .fg = s("#F5C2E7"));
o = (KeyDict_highlight){ .bg = s("#6C7086") };
c("WildMenu");
c("PmenuThumb");
api_free_keydict_highlight(&o);
h("markdownLinkText", .fg = s("#89B4FA"), .underline = True);
h("@comment", .link = s("Comment"));
h("@error", .link = s("Error"));
o = (KeyDict_highlight){ .link = s("PreProc") };
c("Define");
c("@preproc");
c("PreCondit");
api_free_keydict_highlight(&o);
h("@define", .link = s("Define"));
h("@operator", .link = s("Operator"));
h("Folded", .bg = s("#45475A"), .fg = s("#89B4FA"));
h("@string", .link = s("String"));
h("LspDiagnosticsVirtualTextInformation", .fg = s("#89DCEB"), .italic = True);
o = (KeyDict_highlight){ .bg = s("#000000"), .fg = s("#45475A") };
c("TabLine");
c("SignColumnSB");
c("StatusLineNC");
api_free_keydict_highlight(&o);
h("Underlined", .underline = True);
o = (KeyDict_highlight){ .sp = s("#94E2D5"), .underline = True };
c("DiagnosticUnderlineHint");
c("LspDiagnosticsUnderlineHint");
api_free_keydict_highlight(&o);
h("@boolean", .link = s("Boolean"));
o = (KeyDict_highlight){ .link = s("Number") };
c("@float");
c("@number");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("Function") };
c("@function");
c("@method.php");
c("@method.call.php");
api_free_keydict_highlight(&o);
h("@function.call", .link = s("@function"));
h("@method.call", .link = s("@method"));
o = (KeyDict_highlight){ .sp = s("#F9E2AF"), .underline = True };
c("DiagnosticUnderlineWarn");
c("LspDiagnosticsUnderlineWarning");
api_free_keydict_highlight(&o);
h("@text.diff.add", .link = s("diffAdded"));
h("@text.diff.delete", .link = s("diffRemoved"));
o = (KeyDict_highlight){ .link = s("Keyword") };
c("@keyword");
c("@type.qualifier.php");
api_free_keydict_highlight(&o);
h("GitSignsAddPreview", .link = s("DiffAdd"));
h("@conditional", .link = s("Conditional"));
h("@repeat", .link = s("Repeat"));
h("@label", .link = s("Label"));
h("@include", .link = s("Include"));
o = (KeyDict_highlight){ .link = s("Type") };
c("@type");
c("Typedef");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .link = s("@type") };
c("@type.qualifier");
c("@type.definition");
api_free_keydict_highlight(&o);
h("@storageclass", .link = s("StorageClass"));
h("@attribute", .link = s("Constant"));
h("ErrorMsg", .bold = True, .fg = s("#F38BA8"), .italic = True);
h("@constant.macro", .link = s("Macro"));
h("Substitute", .bg = s("#45475A"), .fg = s("#F5C2E7"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#FAB387") };
c("MatchParen");
c("markdownHeadingDelimiter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .sp = s("#89DCEB"), .underline = True };
c("DiagnosticUnderlineInfo");
c("LspDiagnosticsUnderlineInformation");
api_free_keydict_highlight(&o);
h("@text.underline", .link = s("Underline"));
h("@tag.attribute.tsx", .fg = s("#CBA6F7"), .italic = True);
h("Search", .bg = s("#294247"), .fg = s("#CDD6F4"));
h("DiagnosticVirtualTextInfo", .bg = s("#0D1516"), .fg = s("#89DCEB"), .italic = True);
h("IncSearch", .bg = s("#7BC6D4"), .fg = s("#000000"));
o = (KeyDict_highlight){ .bold = True, .fg = s("#CDD6F4") };
c("ModeMsg");
c("CmpItemAbbrMatch");
c("CmpItemAbbrMatchFuzzy");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bg = s("#45475A"), .bold = True };
c("Visual");
c("VisualNOS");
c("QuickFixLine");
api_free_keydict_highlight(&o);
h("SpellBad", .sp = s("#F38BA8"), .undercurl = True);
h("SpellCap", .sp = s("#F9E2AF"), .undercurl = True);
o = (KeyDict_highlight){ .bg = s("#000000"), .fg = s("#000000") };
c("NvimTreeWinSeparator");
c("NvimTreeStatuslineNc");
api_free_keydict_highlight(&o);
h("SpellRare", .sp = s("#A6E3A1"), .undercurl = True);
h("DiffAdd", .bg = s("#1E291D"));
h("DiffDelete", .bg = s("#2C191E"));
h("debugBreakpoint", .bg = s("#000000"), .fg = s("#6C7086"));
h("Todo", .bg = s("#F9E2AF"), .bold = True, .fg = s("#000000"));
o = (KeyDict_highlight){ .sp = s("#F38BA8"), .underline = True };
c("DiagnosticUnderlineError");
c("LspDiagnosticsUnderlineError");
api_free_keydict_highlight(&o);
h("DiffText", .bg = s("#19202D"));
o = (KeyDict_highlight){ .bg = s("#F38BA8"), .fg = s("#000000") };
c("CurSearch");
c("@text.danger");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#FAB387") };
c("Float");
c("Number");
c("Boolean");
c("@method");
c("Constant");
c("@constant");
c("diffNewFile");
c("@number.css");
c("@string.regex");
c("TSRainbowOrange");
c("CmpItemKindValue");
c("@constant.builtin");
c("@function.builtin");
c("@string.plain.css");
c("CmpItemKindConstant");
c("LspSignatureActiveParameter");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F2CDCD") };
c("@event");
c("@symbol");
c("@modifier");
c("@decorator");
c("@interface");
c("Identifier");
c("@enumMember");
c("rainbowcol6");
c("@symbol.ruby");
c("markdownCode");
c("@constructor.lua");
c("markdownCodeBlock");
c("CmpItemKindVariable");
c("NvimTreeSpecialFile");
c("TelescopeSelectionCaret");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#F9E2AF"), .italic = True };
c("DashboardFooter");
c("LspDiagnosticsVirtualTextWarning");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#CBA6F7") };
c("@tag");
c("Macro");
c("Repeat");
c("Keyword");
c("Include");
c("Statement");
c("markdownH2");
c("@exception");
c("Conditional");
c("@type.tag.css");
c("@keyword.return");
c("TSRainbowViolet");
c("@keyword.function");
c("@keyword.operator");
c("CmpItemKindSnippet");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .bold = True, .fg = s("#89B4FA") };
c("Title");
c("htmlH2");
c("@text.title");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#89B4FA") };
c("@class");
c("MoreMsg");
c("@struct");
c("Question");
c("Function");
c("diffFile");
c("Directory");
c("@text.math");
c("qfFileName");
c("FloatBorder");
c("@label.json");
c("@field.yaml");
c("CmpItemKind");
c("rainbowcol4");
c("diffChanged");
c("TSRainbowBlue");
c("LspInfoBorder");
c("GlyphPalette4");
c("NvimTreeGitNew");
c("@property.toml");
c("CmpItemKindFile");
c("@string.special");
c("TelescopeBorder");
c("DashboardHeader");
c("CmpItemKindEvent");
c("@property.id.css");
c("CmpItemKindModule");
c("CmpItemKindFolder");
c("CmpItemKindMethod");
c("CmpItemKindStruct");
c("TelescopeMatching");
c("NvimTreeFolderName");
c("NvimTreeFolderIcon");
c("CmpItemKindOperator");
c("CmpItemKindFunction");
c("@text.environment.name");
c("CmpItemKindConstructor");
c("NvimTreeEmptyFolderName");
c("CmpItemKindTypeParameter");
c("NvimTreeOpenedFolderName");
api_free_keydict_highlight(&o);
o = (KeyDict_highlight){ .fg = s("#89DCEB") };
c("Operator");
c("@tag.delimiter");
c("DiagnosticSignInfo");
c("@punctuation.special");
c("DiagnosticFloatingInfo");
c("LspDiagnosticsInformation");
c("LspDiagnosticsDefaultInformation");
api_free_keydict_highlight(&o);
fprintf(fp, "%f", (double)(clock() - start) / CLOCKS_PER_SEC * 1000);

fclose(fp);
Error_check
}
